services:
  docs:
    networks:
      - fmhy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NITRO_PRESET=node-server
    image: fmhy-docs:latest
    container_name: docs
    restart: unless-stopped
    ports:
      - '4173:4173'
    env_file:
      - .env

networks:
  fmhy:
    driver: bridge
